# Generated by Django 3.0.dev20190905135652 on 2019-09-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('situacao', models.IntegerField(default=0)),
                ('padrao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('datageracao', models.DateTimeField()),
                ('dataefetivacao', models.DateTimeField(blank=True, null=True)),
                ('codigoconta', models.IntegerField(default=0)),
                ('codigosubgrupo', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo', models.IntegerField(default=0)),
                ('situacao', models.IntegerField(default=0)),
                ('codigotransferencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('codigo_grupo', models.IntegerField(default=0)),
            ],
        ),
    ]
