# Generated by Django 3.0.dev20190905135652 on 2019-09-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='codigoconta',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='codigosubgrupo',
        ),
        migrations.RemoveField(
            model_name='subgrupo',
            name='codigo_grupo',
        ),
        migrations.AddField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigoconta', to='financas.Conta'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='subgrupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigosubgrupo', to='financas.SubGrupo'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_grupo', to='financas.Grupo'),
        ),
    ]
