# Generated by Django 3.0.dev20190905135652 on 2019-09-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_auto_20190917_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conta',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1),
        ),
    ]
